# Generated by Django 5.1.6 on 2025-03-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cv',
            options={'verbose_name': 'CV', 'verbose_name_plural': 'CV'},
        ),
        migrations.AlterModelOptions(
            name='cvmark',
            options={'verbose_name': 'CV đã đánh dấu', 'verbose_name_plural': 'CV đã đánh dấu'},
        ),
        migrations.AlterModelOptions(
            name='cvview',
            options={'verbose_name': 'CV đã xem', 'verbose_name_plural': 'CV đã xem'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'Thông tin người dùng', 'verbose_name_plural': 'Thông tin người dùng'},
        ),
    ]
