# Generated by Django 5.1.6 on 2025-04-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_cv_options_alter_cvmark_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='cv_file',
        ),
        migrations.AddField(
            model_name='cv',
            name='cv_file_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='cv_attachments_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
