# Generated by Django 5.1.6 on 2025-03-04 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0001_initial'),
        ('profiles', '0002_cv_cv_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_type', models.CharField(choices=[('interested', 'Quan tâm'), ('shortlisted', 'Vào danh sách ngắn'), ('rejected', 'Từ chối')], max_length=20)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.cv')),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.enterpriseentity')),
            ],
        ),
        migrations.CreateModel(
            name='CvView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.cv')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.enterpriseentity')),
            ],
        ),
    ]
