# Generated by Django 5.1.6 on 2025-04-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_cv_cv_file_cv_cv_file_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
