# Generated by Django 5.1.6 on 2025-05-06 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0022_remove_campaignentity_enterprise_and_more'),
        ('profiles', '0004_cv_is_viewed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cv',
            index=models.Index(fields=['post', 'user'], name='cv_post_user_idx'),
        ),
        migrations.AddIndex(
            model_name='cv',
            index=models.Index(fields=['post', 'status'], name='cv_post_status_idx'),
        ),
        migrations.AddIndex(
            model_name='cv',
            index=models.Index(fields=['user', 'created_at'], name='cv_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='cv',
            index=models.Index(fields=['post'], name='cv_post_idx'),
        ),
        migrations.AddIndex(
            model_name='cv',
            index=models.Index(fields=['created_at'], name='cv_time_idx'),
        ),
    ]
