# Generated by Django 5.1.6 on 2025-03-03 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PositionEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnterpriseEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('business_certificate', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('email_company', models.EmailField(max_length=255)),
                ('field_of_activity', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('link_web_site', models.URLField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, upload_to='enterprise_logos/')),
                ('phone_number', models.CharField(max_length=20)),
                ('scale', models.CharField(max_length=255)),
                ('tax', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprises', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='enterprises.enterpriseentity')),
            ],
        ),
        migrations.CreateModel(
            name='CriteriaEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('scales', models.CharField(max_length=255)),
                ('type_working', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='accounts.user')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='enterprises.fieldentity')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='enterprises.positionentity')),
            ],
        ),
        migrations.CreateModel(
            name='PostEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('district', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('interest', models.TextField()),
                ('level', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('required', models.TextField()),
                ('salary_range', models.CharField(max_length=255)),
                ('time_working', models.CharField(max_length=255)),
                ('type_working', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('detail_address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='enterprises.campaignentity')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='enterprises.positionentity')),
            ],
        ),
    ]
