# Generated by Django 5.1.6 on 2025-03-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignentity',
            options={'verbose_name': 'Chiến dịch', 'verbose_name_plural': 'Chiến dịch'},
        ),
        migrations.AlterModelOptions(
            name='criteriaentity',
            options={'verbose_name': 'Tiêu chí', 'verbose_name_plural': 'Tiêu chí'},
        ),
        migrations.AlterModelOptions(
            name='enterpriseentity',
            options={'verbose_name': 'Doanh nghiệp', 'verbose_name_plural': 'Doanh nghiệp'},
        ),
        migrations.AlterModelOptions(
            name='fieldentity',
            options={'verbose_name': 'Lĩnh vực', 'verbose_name_plural': 'Lĩnh vực'},
        ),
        migrations.AlterModelOptions(
            name='positionentity',
            options={'verbose_name': 'Vị trí', 'verbose_name_plural': 'Vị trí'},
        ),
    ]
