# Generated by Django 5.1.6 on 2025-04-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0003_enterpriseentity_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseentity',
            name='background_image_public_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enterpriseentity',
            name='background_image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enterpriseentity',
            name='logo_public_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enterpriseentity',
            name='logo_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
