# Generated by Django 5.1.6 on 2025-04-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0004_enterpriseentity_background_image_public_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterpriseentity',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='enterpriseentity',
            name='logo',
        ),
    ]
