# Generated by Django 5.1.6 on 2025-04-02 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0006_rename_business_certificate_enterpriseentity_business_certificate_public_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postentity',
            name='campaign',
        ),
        migrations.AddField(
            model_name='postentity',
            name='enterprise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='enterprises.enterpriseentity'),
            preserve_default=False,
        ),
    ]
