# Generated by Django 5.1.6 on 2025-04-03 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0007_remove_postentity_campaign_postentity_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionentity',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='enterprises.fieldentity'),
            preserve_default=False,
        ),
    ]
