# Generated by Django 5.1.6 on 2025-04-04 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0009_alter_campaignentity_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postentity',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='enterprises.fieldentity'),
        ),
    ]
