# Generated by Django 5.1.6 on 2025-04-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0010_postentity_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='postentity',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
