# Generated by Django 5.1.6 on 2025-04-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0012_alter_enterpriseentity_field_of_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postentity',
            name='salary_range',
        ),
        migrations.AddField(
            model_name='postentity',
            name='salary_max',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postentity',
            name='salary_min',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
