# Generated by Django 5.1.6 on 2025-04-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0013_remove_postentity_salary_range_postentity_salary_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postentity',
            name='is_salary_negotiable',
            field=models.BooleanField(default=False),
        ),
    ]
