# Generated by Django 5.1.6 on 2025-04-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0014_postentity_is_salary_negotiable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postentity',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='postentity',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='postentity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='postentity',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postentity',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='postentity',
            name='detail_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='postentity',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postentity',
            name='experience',
            field=models.CharField(db_index=True, default='Không yêu cầu', max_length=50),
        ),
        migrations.AlterField(
            model_name='postentity',
            name='interest',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='postentity',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='postentity',
            name='is_salary_negotiable',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='postentity',
            name='level',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='postentity',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='postentity',
            name='required',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='postentity',
            name='salary_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postentity',
            name='salary_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postentity',
            name='time_working',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='postentity',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='postentity',
            name='type_working',
            field=models.CharField(db_index=True, default='Toàn thời gian', max_length=50),
        ),
        migrations.AddIndex(
            model_name='postentity',
            index=models.Index(fields=['title', 'city', 'experience', 'type_working'], name='posts_title_3735da_idx'),
        ),
        migrations.AddIndex(
            model_name='postentity',
            index=models.Index(fields=['is_active', 'is_salary_negotiable'], name='posts_is_acti_71fa3d_idx'),
        ),
        migrations.AddIndex(
            model_name='postentity',
            index=models.Index(fields=['salary_min', 'salary_max'], name='posts_salary__982792_idx'),
        ),
        migrations.AlterModelTable(
            name='postentity',
            table='posts',
        ),
    ]
