# Generated by Django 5.1.6 on 2025-04-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0015_alter_postentity_options_alter_postentity_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseentity',
            name='background_image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseentity',
            name='business_certificate_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseentity',
            name='business_certificate_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseentity',
            name='link_web_site',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseentity',
            name='logo_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseentity',
            name='logo_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
