# Generated by Django 5.1.6 on 2025-04-07 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0016_alter_enterpriseentity_background_image_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseentity',
            name='city',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='enterpriseentity',
            name='company_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='enterpriseentity',
            name='field_of_activity',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='enterpriseentity',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='enterpriseentity',
            name='scale',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='enterpriseentity',
            index=models.Index(fields=['company_name', 'city'], name='company_city_idx'),
        ),
        migrations.AddIndex(
            model_name='enterpriseentity',
            index=models.Index(fields=['company_name', 'field_of_activity'], name='company_field_idx'),
        ),
        migrations.AddIndex(
            model_name='enterpriseentity',
            index=models.Index(fields=['is_active', 'scale'], name='active_scale_idx'),
        ),
        migrations.AddIndex(
            model_name='enterpriseentity',
            index=models.Index(fields=['created_at'], name='enterprise_created_idx'),
        ),
    ]
