# Generated by Django 5.1.6 on 2025-04-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0017_alter_enterpriseentity_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseentity',
            name='background_image_public_id',
            field=models.CharField(blank=True, default='kpvmqmkdvfytjkh2fjhp', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseentity',
            name='background_image_url',
            field=models.CharField(blank=True, default='https://res.cloudinary.com/dyjo3qdxo/image/upload/v1744163905/enterprise_backgrounds/kpvmqmkdvfytjkh2fjhp.jpg', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseentity',
            name='business_certificate_public_id',
            field=models.CharField(blank=True, default='n_business_certificate', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseentity',
            name='business_certificate_url',
            field=models.CharField(blank=True, default='https://tuyendungtlu.s3.ap-southeast-1.amazonaws.com/n_business_certificate.jpg', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseentity',
            name='logo_public_id',
            field=models.CharField(blank=True, default='tqg6mr5lwx4ecok4y3wz', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseentity',
            name='logo_url',
            field=models.CharField(blank=True, default='https://res.cloudinary.com/dyjo3qdxo/image/upload/v1744163672/enterprise_logos/tqg6mr5lwx4ecok4y3wz.jpg', max_length=255, null=True),
        ),
    ]
