# Generated by Django 5.1.6 on 2025-05-01 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0019_savedpostentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteriaentity',
            name='salary_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='criteriaentity',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='criteriaentity',
            name='experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='criteriaentity',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='enterprises.fieldentity'),
        ),
        migrations.AlterField(
            model_name='criteriaentity',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='enterprises.positionentity'),
        ),
        migrations.AlterField(
            model_name='criteriaentity',
            name='scales',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='criteriaentity',
            name='type_working',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
