# Generated by Django 5.1.6 on 2025-05-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0020_criteriaentity_salary_min_alter_criteriaentity_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postentity',
            name='deadline',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='postentity',
            name='salary_max',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='postentity',
            name='salary_min',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='postentity',
            index=models.Index(fields=['is_active', 'deadline'], name='posts_is_acti_3c9b9e_idx'),
        ),
        migrations.AddIndex(
            model_name='postentity',
            index=models.Index(fields=['position', 'field'], name='posts_positio_3311b9_idx'),
        ),
        migrations.AddIndex(
            model_name='postentity',
            index=models.Index(fields=['enterprise', 'is_active'], name='posts_enterpr_8ccb38_idx'),
        ),
        migrations.AddIndex(
            model_name='postentity',
            index=models.Index(fields=['type_working', 'experience', 'city'], name='posts_type_wo_d7b4e8_idx'),
        ),
    ]
