# Generated by Django 5.1.6 on 2025-05-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0021_alter_postentity_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignentity',
            name='enterprise',
        ),
        migrations.AddIndex(
            model_name='postentity',
            index=models.Index(fields=['field', 'is_active', 'deadline'], name='post_field_active_idx'),
        ),
        migrations.AddIndex(
            model_name='postentity',
            index=models.Index(fields=['position', 'is_active', 'deadline'], name='post_position_active_idx'),
        ),
        migrations.AddIndex(
            model_name='postentity',
            index=models.Index(fields=['city', 'is_active', 'deadline'], name='post_city_active_idx'),
        ),
        migrations.AddIndex(
            model_name='postentity',
            index=models.Index(fields=['enterprise', 'is_active', 'deadline'], name='post_enterprise_active_idx'),
        ),
        migrations.AddIndex(
            model_name='postentity',
            index=models.Index(fields=['field', 'position'], name='post_field_position_idx'),
        ),
        migrations.AddIndex(
            model_name='postentity',
            index=models.Index(fields=['field', 'city'], name='post_field_city_idx'),
        ),
        migrations.AddIndex(
            model_name='postentity',
            index=models.Index(fields=['position', 'city'], name='post_position_city_idx'),
        ),
        migrations.AddIndex(
            model_name='postentity',
            index=models.Index(fields=['is_active', 'deadline', 'created_at'], name='post_active_date_created_idx'),
        ),
        migrations.DeleteModel(
            name='CampaignEntity',
        ),
    ]
