# Generated by Django 5.1.6 on 2025-05-03 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(default='Cuộc trò chuyện mới', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gemini_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phiên chat Gemini',
                'verbose_name_plural': 'Phiên chat Gemini',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GeminiChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('model', 'Gemini Model'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='gemini_chat.geminichatsession')),
            ],
            options={
                'verbose_name': 'Tin nhắn Gemini',
                'verbose_name_plural': 'Tin nhắn Gemini',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='geminichatsession',
            index=models.Index(fields=['user', 'created_at'], name='gemini_chat_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='geminichatmessage',
            index=models.Index(fields=['session', 'created_at'], name='gemini_msg_session_time_idx'),
        ),
    ]
