# Generated by Django 5.1.6 on 2025-05-03 16:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemini_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geminichatmessage',
            options={'ordering': ['timestamp'], 'verbose_name': 'Tin nhắn Gemini', 'verbose_name_plural': 'Tin nhắn Gemini'},
        ),
        migrations.RemoveIndex(
            model_name='geminichatmessage',
            name='gemini_msg_session_time_idx',
        ),
        migrations.RenameField(
            model_name='geminichatmessage',
            old_name='session',
            new_name='chat_session',
        ),
        migrations.RenameField(
            model_name='geminichatmessage',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='geminichatsession',
            name='session_id',
        ),
        migrations.AlterField(
            model_name='geminichatmessage',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Gemini Assistant'), ('system', 'System')], max_length=10),
        ),
        migrations.AlterField(
            model_name='geminichatsession',
            name='title',
            field=models.CharField(default='Phiên chat mới', max_length=255),
        ),
        migrations.AddIndex(
            model_name='geminichatmessage',
            index=models.Index(fields=['chat_session', 'timestamp'], name='gemini_msg_session_time_idx'),
        ),
    ]
