# Generated by Django 5.1.6 on 2025-03-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Vai trò', 'verbose_name_plural': 'Vai trò'},
        ),
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'Tài khoản', 'verbose_name_plural': 'Tài khoản'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'Vai trò', 'verbose_name_plural': 'Vai trò'},
        ),
    ]
