# Generated by Django 5.1.6 on 2025-04-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraccount_activation_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'Vai trò người dùng', 'verbose_name_plural': 'Vai trò người dùng'},
        ),
    ]
