# Generated by Django 5.1.6 on 2025-04-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userrole_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
