# Generated by Django 5.1.6 on 2025-04-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_useraccount_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
