# Generated by Django 5.1.6 on 2025-03-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historymoney',
            options={'verbose_name': 'Lịch sử giao dịch', 'verbose_name_plural': 'Lịch sử giao dịch'},
        ),
    ]
