# Generated by Django 5.1.6 on 2025-04-16 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_historymoney_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VnPayTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('transaction_no', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_status', models.CharField(blank=True, max_length=255, null=True)),
                ('order_info', models.CharField(blank=True, max_length=255, null=True)),
                ('txn_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vnpay_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Giao dịch VnPay',
                'verbose_name_plural': 'Giao dịch VnPay',
            },
        ),
    ]
