# Generated by Django 5.1.6 on 2025-04-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_premiumpackage_premiumhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumpackage',
            name='name_display',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
