# Generated by Django 5.1.6 on 2025-04-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_premiumpackage_name_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumpackage',
            name='can_chat_with_employers',
            field=models.BooleanField(default=False, help_text='Cho phép chat với nhà tuyển dụng'),
        ),
        migrations.AddField(
            model_name='premiumpackage',
            name='can_feature_posts',
            field=models.BooleanField(default=False, help_text='Cho phép đăng bài nổi bật'),
        ),
        migrations.AddField(
            model_name='premiumpackage',
            name='can_view_job_applications',
            field=models.BooleanField(default=False, help_text='Cho phép xem số người ứng tuyển của bài viết'),
        ),
        migrations.AddField(
            model_name='premiumpackage',
            name='daily_job_application_limit',
            field=models.IntegerField(default=5, help_text='Số lượng đơn ứng tuyển có thể gửi mỗi ngày'),
        ),
        migrations.AddField(
            model_name='premiumpackage',
            name='max_cv_views_per_day',
            field=models.IntegerField(default=10, help_text='Số lượng CV có thể xem mỗi ngày'),
        ),
        migrations.AddField(
            model_name='premiumpackage',
            name='max_job_posts',
            field=models.IntegerField(default=3, help_text='Số lượng bài đăng tuyển dụng tối đa'),
        ),
        migrations.AddField(
            model_name='premiumpackage',
            name='priority_in_search',
            field=models.IntegerField(default=0, help_text='Độ ưu tiên khi hiển thị trong tìm kiếm (0=thấp, 10=cao)'),
        ),
    ]
