# Generated by Django 5.1.6 on 2025-04-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_premiumpackage_can_chat_with_employers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumpackage',
            name='can_view_submitted_cvs',
            field=models.BooleanField(default=True, help_text='Cho phép xem số CV đã nộp vào bài đăng'),
        ),
    ]
