# Generated by Django 5.1.6 on 2025-04-22 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_useraccount_cv_views_today_and_more'),
        ('transactions', '0007_premiumpackage_can_view_submitted_cvs'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumpackage',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='premium_packages', to='accounts.role'),
            preserve_default=False,
        ),
    ]
