# Generated by Django 5.1.6 on 2025-05-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_premiumpackage_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumpackage',
            name='priority_coefficient',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
