# Generated by Django 5.1.6 on 2025-05-01 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_premiumpackage_priority_coefficient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='premiumhistory',
            index=models.Index(fields=['user', 'is_active', 'is_cancelled', 'end_date'], name='premium_status_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumhistory',
            index=models.Index(fields=['user', 'created_at'], name='premium_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumhistory',
            index=models.Index(fields=['is_active', 'end_date'], name='premium_active_date_idx'),
        ),
    ]
