# Generated by Django 5.1.6 on 2025-03-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['-interview_date'], 'verbose_name': 'Cuộc phỏng vấn', 'verbose_name_plural': 'Cuộc phỏng vấn'},
        ),
    ]
