# Generated by Django 5.1.6 on 2025-03-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Thông báo', 'verbose_name_plural': 'Thông báo'},
        ),
    ]
